kernel:
  image: linuxkit/kernel:5.10.47
  cmdline: "console=ttyS0"

init:
  - linuxkit/init:v0.8
  - linuxkit/runc:v0.8
  - linuxkit/containerd:v0.8

onboot:
  - name: sysctl
    image: linuxkit/sysctl:v0.8
    command: ["/sbin/sysctl", "-w", "kernel.printk=8"]

services:
  - name: getty
    image: linuxkit/getty:v0.8
    env:
      - INSECURE=true
    command: ["/sbin/getty", "console"]

files:
  - path: root/.ssh/authorized_keys
    source: ~/.ssh/id_rsa.pub
    mode: "0600"
